# Generated by Django 5.2.8 on 2025-12-16 05:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_unico', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('hash_validacion', models.CharField(blank=True, max_length=256)),
                ('fecha_generado', models.DateTimeField(blank=True, null=True)),
                ('fecha_enviado', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('NO_GENERADO', 'No generado'), ('GENERADO', 'Generado'), ('ENVIADO', 'Enviado')], default='NO_GENERADO', max_length=20)),
                ('qr_imagen', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('enviado_email', models.BooleanField(default=False)),
                ('trabajador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_registro', to='trabajadores.trabajador')),
            ],
            options={
                'verbose_name': 'Registro QR',
                'verbose_name_plural': 'Registros QR',
                'db_table': 'qr_registros',
            },
        ),
    ]
