# Generated by Django 5.2.8 on 2025-12-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(help_text='Formato: 12345678-9', max_length=12, unique=True, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('cargo', models.CharField(help_text='Ej: Operario, Supervisor, Jefe de Turno', max_length=150, verbose_name='Cargo')),
                ('tipo_contrato', models.CharField(choices=[('indefinido', 'Indefinido'), ('plazo_fijo', 'A Plazo Fijo')], max_length=20, verbose_name='Tipo de Contrato')),
                ('periodo', models.CharField(help_text='Ej: Enero 2024 - Diciembre 2024', max_length=50, verbose_name='Período')),
                ('sede', models.CharField(help_text='Ej: Casa Matriz, Sucursal Norte', max_length=100, verbose_name='Sede')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('retirado', 'Retirado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
                'db_table': 'trabajadores',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombre'],
            },
        ),
    ]
