# Generated by Django 5.2.8 on 2025-12-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='area',
            field=models.CharField(choices=[('produccion_manufactura', 'Producción y Manufactura'), ('logistica_distribucion', 'Logística y Distribución'), ('administracion', 'Administración'), ('rrhh', 'Recursos Humanos'), ('ingenieria_practicas', 'Ingeniería y Prácticas')], default='produccion_manufactura', help_text='Área o departamento al que pertenece', max_length=50, verbose_name='Área/Departamento'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='email',
            field=models.EmailField(blank=True, help_text='Correo electrónico del trabajador', max_length=255, null=True, verbose_name='Email'),
        ),
    ]
