# Generated by Django 5.2.8 on 2025-12-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0002_trabajador_area_trabajador_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='qr_codigo',
            field=models.CharField(blank=True, help_text='Ruta o identificador del archivo QR generado', max_length=255, null=True, verbose_name='Código QR'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='qr_fecha_generacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se generó el QR', null=True, verbose_name='Fecha Generación QR'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='qr_generado',
            field=models.BooleanField(default=False, help_text='Indica si se generó el código QR para este trabajador', verbose_name='QR Generado'),
        ),
    ]
