# Generated by Django 5.2.8 on 2025-12-21 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Producción y Manufactura, Logística', max_length=150, unique=True, verbose_name='Nombre del Área')),
                ('codigo', models.CharField(help_text='Código interno del área (ej: produccion_manufactura)', max_length=50, unique=True, verbose_name='Código')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del área o departamento', null=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, help_text='Indica si el área está activa', verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'db_table': 'areas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Casablanca, Valparaíso – Planta BIF', max_length=150, unique=True, verbose_name='Nombre de la Sucursal')),
                ('codigo', models.CharField(help_text='Código interno de la sucursal (ej: CASA, VBIF, VBIC)', max_length=20, unique=True, verbose_name='Código')),
                ('direccion', models.CharField(blank=True, help_text='Dirección física de la sucursal', max_length=255, null=True, verbose_name='Dirección')),
                ('activa', models.BooleanField(default=True, help_text='Indica si la sucursal está activa', verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sucursales_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'sucursales',
                'ordering': ['nombre'],
            },
        ),
    ]
