# Generated by Django 5.2.8 on 2025-12-14 20:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('entregas', 'Entregas'), ('trabajadores', 'Trabajadores'), ('incidencias', 'Incidencias'), ('stock', 'Stock de Cajas'), ('auditoria', 'Auditoría')], max_length=20)),
                ('formato', models.CharField(choices=[('excel', 'Excel'), ('pdf', 'PDF'), ('csv', 'CSV')], default='excel', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reportes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EjecucionReporte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('fallido', 'Fallido')], default='pendiente', max_length=20)),
                ('archivo_nombre', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='reportes.reporte')),
            ],
            options={
                'db_table': 'ejecuciones_reportes',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
