# Generated by Django 5.2.8 on 2025-12-06 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entregas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('qr_no_funciona', 'QR no funciona'), ('trabajador_no_registrado', 'Trabajador no registrado'), ('caja_danada', 'Caja dañada'), ('stock_insuficiente', 'Stock insuficiente'), ('trabajador_sin_beneficio', 'Trabajador sin derecho a beneficio'), ('incompatibilidad_contrato', 'Incompatibilidad de contrato'), ('sistema_caido', 'Sistema caído'), ('otro', 'Otro')], max_length=30, verbose_name='Tipo de Incidencia')),
                ('descripcion', models.TextField(help_text='Descripción detallada del problema', verbose_name='Descripción')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10, verbose_name='Prioridad')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('resuelto', 'Resuelto'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Reporte')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Resolución')),
                ('solucion', models.TextField(blank=True, help_text='Descripción de cómo se resolvió la incidencia', verbose_name='Solución')),
                ('rut_trabajador_manual', models.CharField(blank=True, help_text='RUT del trabajador si no se pudo escanear QR', max_length=12, verbose_name='RUT ingresado manualmente')),
                ('imagen_evidencia', models.ImageField(blank=True, help_text='Foto del problema (opcional)', null=True, upload_to='incidencias/%Y/%m/', verbose_name='Imagen de Evidencia')),
                ('notificado', models.BooleanField(default=False, help_text='Si se notificó al supervisor', verbose_name='Notificado a Supervisor')),
                ('entrega_relacionada', models.ForeignKey(blank=True, help_text='Entrega asociada a esta incidencia', null=True, on_delete=django.db.models.deletion.SET_NULL, to='entregas.entrega', verbose_name='Entrega Relacionada')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'ordering': ['-fecha_reporte'],
            },
        ),
    ]
