# Generated by Django 5.2.8 on 2025-12-06 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidencias', '0001_initial'),
        ('trabajadores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='guardia',
            field=models.ForeignKey(limit_choices_to={'rol': 'guardia'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_reportadas', to=settings.AUTH_USER_MODEL, verbose_name='Guardia que reporta'),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_resueltas', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor que resuelve'),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='trabajador',
            field=models.ForeignKey(blank=True, help_text='Trabajador relacionado con la incidencia', null=True, on_delete=django.db.models.deletion.CASCADE, to='trabajadores.trabajador', verbose_name='Trabajador'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['-fecha_reporte'], name='incidencias_fecha_r_17dec8_idx'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['estado', '-fecha_reporte'], name='incidencias_estado_c6beff_idx'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['prioridad', 'estado'], name='incidencias_priorid_a147c3_idx'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['guardia', '-fecha_reporte'], name='incidencias_guardia_fdd3e5_idx'),
        ),
    ]
