# Generated by Django 5.2.8 on 2025-12-21 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Entrega Navidad 2025', max_length=200, verbose_name='Nombre de la Campaña')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional de la campaña', null=True, verbose_name='Descripción')),
                ('sucursal', models.CharField(choices=[('casablanca', 'Casablanca'), ('valparaiso_bif', 'Valparaíso – Planta BIF'), ('valparaiso_bic', 'Valparaíso – Planta BIC')], max_length=50, verbose_name='Sucursal')),
                ('tipo_entrega', models.CharField(choices=[('general', 'General (Todas las áreas)'), ('grupo', 'Por Grupo (Áreas específicas)')], default='general', max_length=20, verbose_name='Tipo de Entrega')),
                ('areas_seleccionadas', models.JSONField(default=list, help_text='Lista de áreas habilitadas para esta campaña', verbose_name='Áreas Seleccionadas')),
                ('tipo_contrato', models.CharField(choices=[('indefinido', 'Indefinido'), ('plazo_fijo', 'Plazo Fijo')], max_length=20, verbose_name='Tipo de Contrato')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('activa', models.BooleanField(default=True, help_text='Indica si la campaña está actualmente activa', verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
            ],
            options={
                'verbose_name': 'Campaña de Entrega',
                'verbose_name_plural': 'Campañas de Entrega',
                'db_table': 'campanas_entrega',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
