# Generated by Django 5.2.8 on 2025-12-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanaentrega',
            name='tipo_contrato',
            field=models.JSONField(default=list, help_text='Lista de tipos de contrato habilitados: indefinido, plazo_fijo', verbose_name='Tipos de Contrato'),
        ),
        migrations.AlterField(
            model_name='campanaentrega',
            name='tipo_entrega',
            field=models.CharField(choices=[('general', 'General (Todas las áreas)'), ('grupo', 'Por Grupo (Áreas específicas)')], default='general', max_length=50, verbose_name='Tipo de Entrega'),
        ),
    ]
