# Generated by Django 5.2.8 on 2025-12-06 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cajas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Entrega')),
                ('estado', models.CharField(choices=[('entregado', 'Entregado'), ('no_entregado', 'No Entregado'), ('pendiente', 'Pendiente')], default='entregado', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('codigo_qr_trabajador', models.CharField(blank=True, max_length=100, verbose_name='Código QR Trabajador')),
                ('codigo_qr_caja', models.CharField(blank=True, max_length=100, verbose_name='Código QR Caja')),
                ('validado_supervisor', models.BooleanField(default=False, verbose_name='Validado por Supervisor')),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Validación')),
                ('caja', models.ForeignKey(help_text='Caja específica que se entrega', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cajas.caja', verbose_name='Caja Entregada')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'ordering': ['-fecha_entrega'],
            },
        ),
    ]
