# Generated by Django 5.2.8 on 2025-12-06 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entregas', '0001_initial'),
        ('trabajadores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='guardia',
            field=models.ForeignKey(help_text='Guardia que realiza la entrega', limit_choices_to={'rol': 'guardia'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Guardia'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_validadas', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='trabajador',
            field=models.ForeignKey(help_text='Trabajador que recibe la caja', on_delete=django.db.models.deletion.CASCADE, to='trabajadores.trabajador', verbose_name='Trabajador'),
        ),
        migrations.AddIndex(
            model_name='entrega',
            index=models.Index(fields=['-fecha_entrega'], name='entregas_en_fecha_e_9841f4_idx'),
        ),
        migrations.AddIndex(
            model_name='entrega',
            index=models.Index(fields=['trabajador', '-fecha_entrega'], name='entregas_en_trabaja_355a5b_idx'),
        ),
        migrations.AddIndex(
            model_name='entrega',
            index=models.Index(fields=['guardia', '-fecha_entrega'], name='entregas_en_guardia_e5f8e3_idx'),
        ),
        migrations.AddIndex(
            model_name='entrega',
            index=models.Index(fields=['estado'], name='entregas_en_estado_942bd0_idx'),
        ),
    ]
