# Generated by Django 5.2.8 on 2025-12-22 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='leido',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='trabajador',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='datos_extra',
            field=models.JSONField(blank=True, default=dict, help_text='Información adicional en formato JSON', verbose_name='Datos Adicionales'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='leida',
            field=models.BooleanField(default=False, verbose_name='Leída'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='leida_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Lectura'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10, verbose_name='Prioridad'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='usuario_destinatario',
            field=models.ForeignKey(blank=True, help_text='Si es None, es para todos los RRHH', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='mensaje',
            field=models.TextField(verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('resumen_entregas', 'Resumen de Entregas'), ('incidencia_nueva', 'Incidencia Nueva'), ('stock_bajo', 'Stock Bajo'), ('campana_vence', 'Campaña Próxima a Vencer'), ('trabajador_nuevo', 'Trabajador Nuevo')], max_length=30, verbose_name='Tipo de Notificación'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['-creado_en'], name='notificacio_creado__2c5be9_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['tipo', '-creado_en'], name='notificacio_tipo_b01bb2_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['leida', '-creado_en'], name='notificacio_leida_5b016b_idx'),
        ),
    ]
