# Generated by Django 5.2.8 on 2025-12-22 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sucursal',
            field=models.CharField(choices=[('casablanca', 'Casablanca'), ('valparaiso_bif', 'Valparaíso – Planta BIF'), ('valparaiso_bic', 'Valparaíso – Planta BIC')], default='casablanca', help_text='Sucursal a la que pertenece el usuario', max_length=50, verbose_name='Sucursal'),
        ),
    ]
