# Generated by Django 5.2.8 on 2025-12-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('tipo_contrato', models.CharField(choices=[('indefinido', 'Indefinido'), ('plazo_fijo', 'Plazo Fijo')], max_length=20)),
                ('sucursal', models.CharField(choices=[('casablanca', 'Casablanca'), ('valparaiso_bif', 'Valparaíso – Planta BIF'), ('valparaiso_bic', 'Valparaíso – Planta BIC')], max_length=50)),
                ('cantidad_disponible', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
            },
        ),
    ]
